server:
  port: 8189
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accdb?currentSchema=java_pro
    username: sa
    password: sa
  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true



